import { DEMO_STORIES } from './data/demo.js';
import { buildDailyBrief } from './data/select.js';
import { AI_LEADERS, COUNTRY_DEEP_DIVE } from './data/sourceRegistry.js';
const brief=buildDailyBrief(DEMO_STORIES);
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function card(s,compact=false){return `<article class="story-card ${compact?'compact':''}"><div class="story-meta"><span class="score">TBAR ${s.tbarScore}</span><span>${esc(s.sourceName)}</span></div><h3>${esc(s.title)}</h3><p>${esc(s.executiveSummary)}</p>${compact?'':`<div class="insight"><strong>Why it matters</strong><span>${esc(s.whyItMatters)}</span></div><div class="insight taiwan"><strong>Taiwan lens</strong><span>${esc(s.taiwanImpact)}</span></div>`}</article>`;}
function section(n,title,limit,items,compact=false){return `<section><div class="section-title"><h2>${n}. ${title}</h2><span>${limit}</span></div><div class="grid">${items.map(x=>card(x,compact)).join('')}</div></section>`;}
document.querySelector('#root').innerHTML=`<main class="app-shell"><header class="topbar"><div><div class="brand">TBAR</div><div class="subtitle">Taiwan Business & AI Radar</div></div><div class="live-dot"><i></i>TIMELY</div></header><section class="hero"><span class="eyebrow">TODAY</span><h1>What matters. Nothing more.</h1><p>AI + business intelligence filtered through a Taiwan lens.</p></section>${section(1,'Must Know','≤ 3',brief.mustKnow)}${section(2,'Important Signals','≤ 5',brief.importantSignals,true)}${section(3,'Deep Dive','0–2',brief.deepDive)}<div class="country-row">${COUNTRY_DEEP_DIVE.map(c=>`<span>${c}</span>`).join('')}</div>${section(4,'Watchlist','living signals',brief.watchlist,true)}<section class="leaders"><div class="section-title"><h2>AI Leader Radar</h2><span>10 leaders</span></div><div class="chips">${AI_LEADERS.map(p=>`<span>${p}</span>`).join('')}</div></section><footer>TBAR V0.1 · Data-first build</footer></main>`;
if('serviceWorker' in navigator) window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(console.error));
