/* Project Eddie V19 patch: student-facing Chinese UX + direct replacement + simple help request */
S.changes=S.changes||{};
let replacePending=null;
function zhStatus(uid){return status(uid)==='confirmed'?'已確認':status(uid)==='change'?'申請改時間':'待確認'}
function closeReplace(){const m=document.getElementById('replaceBack');if(m)m.classList.remove('show');replacePending=null}
function ensureReplaceModal(){if(document.getElementById('replaceBack'))return;const div=document.createElement('div');div.id='replaceBack';div.className='replaceBack';div.innerHTML='<div class="replaceModal"><small>更換已選時段</small><h3 id="replaceTitle">要取代哪一堂？</h3><p id="replaceText"></p><div class="replaceList" id="replaceList"></div><button class="btn replaceCancel" id="replaceCancel">取消</button></div>';document.body.appendChild(div);document.getElementById('replaceCancel').onclick=closeReplace;div.onclick=e=>{if(e.target===div)closeReplace()}}
function showReplacePicker(newId,arr,s){ensureReplaceModal();replacePending={newId,arr:[...arr],studentId:s.id};$('replaceTitle').textContent='要用 '+fmt(newId)+' 取代哪一堂？';$('replaceText').textContent='你已經選滿 '+arr.length+' 堂。直接點下面其中一堂，就會換成新的時間。';$('replaceList').innerHTML=arr.map(oldId=>'<button class="replaceChoice" data-old="'+oldId+'">取代 '+fmt(oldId)+'</button>').join('');document.querySelectorAll('.replaceChoice').forEach(b=>b.onclick=()=>{const p=replacePending;if(!p)return;let cur=drafts(p.studentId);cur=cur.map(x=>x===b.dataset.old?p.newId:x);S.drafts[p.studentId]=cur;save();closeReplace();renderStudent()});$('replaceBack').classList.add('show')}
renderAggregation=function(){let c=0,w=0,ch=0;$('aggBody').innerHTML=S.students.map(s=>{let z=status(s.id);if(z==='confirmed')c++;else if(z==='change')ch++;else w++;let li=S.line[s.id]?.sent?(S.line[s.id].reminded?'已提醒':'已送出'):'尚未送出';let req=S.changes[s.id],sch=scheduleSummary(s),acts='—';if(req){if(req.help){sch+=' → <span class="helpFlag">請 Eddie 幫忙安排</span>'+(req.from?' · 原時段 '+fmt(req.from):'')+(req.note?' · 備註：'+req.note:'');acts='<div class="actions"><button class="btn mini" data-keep="'+s.id+'">保留原時間</button></div>'}else if(req.to){sch+=' → 想改成 '+fmt(req.to);acts='<div class="actions"><button class="btn green mini" data-approve="'+s.id+'">同意更改</button><button class="btn mini" data-keep="'+s.id+'">保留原時間</button></div>'}}return '<tr><td><b>'+s.name+'</b></td><td>'+sch+'</td><td><span class="status '+z+'">'+zhStatus(s.id)+'</span></td><td>'+li+'</td><td>'+acts+'</td></tr>'}).join('');$('stConfirmed').textContent=c;$('stWaiting').textContent=w;$('stChange').textContent=ch;$('cConfirmed').textContent=c;$('cWaiting').textContent=w;$('cChange').textContent=ch;document.querySelectorAll('[data-keep]').forEach(b=>b.onclick=()=>{let u=b.dataset.keep;delete S.changes[u];S.confirm[u]='confirmed';save();render()});document.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>approveChange(b.dataset.approve));renderLineAction()};
renderStudent=function(){let s=st(),allowed=new Set(choicesFor(s)),b=bookings(s.id),dr=drafts(s.id).filter(id=>allowed.has(id)),z=status(s.id),req=S.changes[s.id],need=Math.max(0,s.sessions-b.length),out='<div class="head"></div>'+D.map(x=>'<div class="head">'+x+'</div>').join('');S.drafts[s.id]=dr;$('hello').textContent='嗨，'+s.name+' 👋';$('portalProgress').textContent='本週 '+b.length+' / '+s.sessions+' 堂 · '+zhStatus(s.id);let step='',title='',text='',action='';
if(req){step='已送出改課需求';if(req.help){title='已通知 Eddie 幫你安排';text=(req.from?'原本 '+fmt(req.from)+' 先幫你保留。':'目前時段先保留。')+(req.note?' 你的備註：'+req.note:'');action='<button class="btn" disabled>等待 Eddie 回覆</button>'}else{title='等待 Eddie 確認';text=fmt(req.from)+' → '+fmt(req.to)+'。Eddie 同意前，原時段仍然保留。';action='<button class="btn" disabled>等待 Eddie 確認</button>'}}
else if(changeMode){step='臨時改時間';if(!changeFrom){title='先選要更改的原時段';text='點下面你已確認的粉紅色時段。';action='<div class="guideActions"><button class="btn" id="cancelChange">取消</button></div>'}else{title='再選一個新的時間';text='直接點下面有空的時段；如果沒有適合的，就請 Eddie 幫你安排。';action='<div class="guideActions"><input class="helpNote" id="changeNote" placeholder="可選填，例如：週三下午比較方便"><button class="btn amber" id="askEddie">請 Eddie 幫我安排</button><button class="btn" id="cancelChange">取消</button></div>'}}
else if(z==='confirmed'){step='本週已確認';title='你的本週課程已確認 ✓';text=b.map(fmt).join(' · ');action='<button class="btn amber" id="requestChange">🔄 這週臨時改時間</button>'}
else if(need>0){step='步驟 1 — 選擇 '+need+' 個時間';title=dr.length?'目前已選：'+dr.map(fmt).join(' · '):'請選擇上課時間';text=dr.length===need?(need===1?'想換別的時間？直接點新的粉紅時段，會自動替換。':'如果想換其中一堂，直接點新的粉紅時段，再選要被取代的那一堂。'):'直接點下面粉紅色「點這裡選擇」的時段。';action='<button class="btn primary" id="confirmChoice" '+(dr.length!==need?'disabled':'')+'>✅ 確認本週課程</button>'}
else{step='步驟 2 — 確認';title='請確認本週課程';text=b.map(fmt).join(' · ');action='<button class="btn primary" id="confirmWeek">✅ 確認本週課程</button>'}
$('guideStep').textContent=step;$('guideTitle').textContent=title;$('guideText').textContent=text;$('guideAction').innerHTML=action;
for(const h of H){out+='<div class="time">'+hh(h)+'<br>'+hh(h+1)+'</div>';for(let d=0;d<5;d++){let id=sid(d,h),cl='unavailable',t='不可選',sub='此時段目前不可使用';if(b.includes(id)){cl=changeMode?'changeFrom':'mine';t=changeMode?(changeFrom===id?'✓ 要更改這一堂':'點這堂來更改'):'✓ 已確認';sub=fmt(id)}else if(changeMode&&changeFrom&&!owner(id)&&!coachTime(h)){cl='changeTarget';t='點這裡改成此時段';sub=fmt(id)}else if(need>0&&allowed.has(id)){cl=dr.includes(id)?'selectedChoice':'allowed';t=dr.includes(id)?'已選擇':'點這裡選擇';sub=dr.includes(id)?fmt(id)+' · 再點可取消':fmt(id)}out+='<div class="sSlot '+cl+'" data-id="'+id+'"><div class="sCell"><b>'+t+'</b><small>'+sub+'</small></div></div>'}}$('studentCal').innerHTML=out;
if(!changeMode){document.querySelectorAll('#studentCal .allowed,#studentCal .selectedChoice').forEach(el=>el.onclick=()=>{let id=el.dataset.id,arr=drafts(s.id);if(arr.includes(id)){arr=arr.filter(x=>x!==id);S.drafts[s.id]=arr;save();renderStudent();return}if(arr.length<need){arr=[...arr,id];S.drafts[s.id]=arr;save();renderStudent();return}if(arr.length===need&&need===1){S.drafts[s.id]=[id];save();renderStudent();return}if(arr.length===need&&need>1){showReplacePicker(id,arr,s)}})}else{document.querySelectorAll('#studentCal .changeFrom').forEach(el=>el.onclick=()=>{changeFrom=el.dataset.id;renderStudent()});document.querySelectorAll('#studentCal .changeTarget').forEach(el=>el.onclick=()=>{if(!changeFrom)return;S.changes[s.id]={from:changeFrom,to:el.dataset.id,help:false};S.confirm[s.id]='change';changeMode=false;changeFrom=null;save();render()})}
let cc=$('confirmChoice');if(cc)cc.onclick=()=>{let arr=drafts(s.id);if(arr.length!==need)return;for(const id of arr){if(!allowed.has(id))return;S.bookings[id]={studentId:s.id}}if(s.mode==='choices')Object.keys(S.holds).forEach(k=>{if(S.holds[k]?.studentId===s.id)delete S.holds[k]});delete S.drafts[s.id];S.confirm[s.id]='confirmed';save();render()};let cw=$('confirmWeek');if(cw)cw.onclick=()=>{S.confirm[s.id]='confirmed';save();render()};let rc=$('requestChange');if(rc)rc.onclick=()=>{changeMode=true;changeFrom=b.length===1?b[0]:null;renderStudent()};let cancel=$('cancelChange');if(cancel)cancel.onclick=()=>{changeMode=false;changeFrom=null;renderStudent()};let ask=$('askEddie');if(ask)ask.onclick=()=>{if(!changeFrom)return;let note=($('changeNote')?.value||'').trim();S.changes[s.id]={from:changeFrom,to:null,help:true,note};S.confirm[s.id]='change';changeMode=false;changeFrom=null;save();render()}}
ensureReplaceModal();render();