/* Project Eddie V20: instant live-availability change + coach red alert; no approval for conflict-free changes */
S.notifications=S.notifications||[];S.weeklyOverrides=S.weeklyOverrides||{};S.lastChange=S.lastChange||{};
function v20FixedOwner(id){const hit=Object.entries(S.fixed||{}).find(([uid,ids])=>(ids||[]).includes(id));if(!hit)return null;const uid=hit[0],ov=S.weeklyOverrides[uid];if(ov&&ov.from===id)return null;return uid}
fixedOwner=v20FixedOwner;
owner=function(id){return book(id)?.studentId||hold(id)?.studentId||v20FixedOwner(id)||null};
function unreadNotes(){return (S.notifications||[]).filter(n=>!n.seen)}
function addChangeNote(s,from,to){S.notifications.push({id:'chg-'+Date.now()+'-'+Math.random().toString(36).slice(2,7),studentId:s.id,type:'change',from,to,seen:false,createdAt:Date.now(),coachLine:true});S.lastChange[s.id]={from,to,createdAt:Date.now()}}
function ensureCoachAlerts(){if($('coachAlerts'))return;const box=document.createElement('div');box.id='coachAlerts';box.className='coachAlerts';const target=document.querySelector('#coachPanel .confirmWrap');target.parentNode.insertBefore(box,target)}
function renderCoachAlerts(){ensureCoachAlerts();const box=$('coachAlerts'),notes=unreadNotes().slice().sort((a,b)=>b.createdAt-a.createdAt);if(!notes.length){box.classList.remove('show');box.innerHTML='';return}box.classList.add('show');box.innerHTML='<div class="alertHead"><div><div class="alertTitle"><span class="redDot"></span>NEW · '+notes.length+' 個課程異動</div><div class="alertSub">學生已從即時空檔自行完成改課；Eddie 不需批准，但請確認已看到。</div></div>'+(notes.length>1?'<button class="btn mini" id="ackAll">✓ 全部知道了</button>':'')+'</div><div class="alertList">'+notes.map(n=>{const s=byId(n.studentId);return '<div class="alertItem"><div><b><span class="alertBadge">NEW</span>'+(s?.name||'Student')+' 已改課</b><small>'+fmt(n.from)+' → '+fmt(n.to)+' · 已自動確認 · LINE 通知 Eddie（正式串接後）</small></div><button class="btn mini" data-ack="'+n.id+'">✓ 我知道了</button></div>'}).join('')+'</div>';document.querySelectorAll('[data-ack]').forEach(b=>b.onclick=()=>{const n=S.notifications.find(x=>x.id===b.dataset.ack);if(n)n.seen=true;save();render()});const all=$('ackAll');if(all)all.onclick=()=>{S.notifications.forEach(n=>n.seen=true);save();render()}}
function autoChange(uid,from,to){const s=byId(uid);if(!s)return false;const currentOwner=owner(to);if(currentOwner&&currentOwner!==uid){alert('這個時段剛剛已被選走，請重新選擇。');renderStudent();return false}if(!book(from)||book(from).studentId!==uid){alert('原本的課程狀態已改變，畫面會重新整理。');render();return false}delete S.bookings[from];S.bookings[to]={studentId:uid};if(s.mode==='fixed'){const regular=S.fixed[uid]||[],existing=S.weeklyOverrides[uid];const original=existing?.from||regular.find(id=>id===from)||regular[0]||null;if(regular.includes(to)){delete S.weeklyOverrides[uid]}else if(original){S.weeklyOverrides[uid]={from:original,to}}}delete S.changes[uid];S.confirm[uid]='confirmed';addChangeNote(s,from,to);changeMode=false;changeFrom=null;save();render();return true}
function liveTargets(s,from){const ids=[];for(let d=0;d<5;d++)for(const h of H){const id=sid(d,h);if(id===from||coachTime(h))continue;if(!owner(id))ids.push(id)}return ids}
const v19Aggregation=renderAggregation;
renderAggregation=function(){v19Aggregation();const notes=unreadNotes(),pending=S.students.filter(s=>status(s.id)==='change').length,total=notes.length+pending;$('cChange').textContent=total;$('stChange').textContent=total;const p=$('cChange')?.parentElement;if(p&&p.firstChild)p.firstChild.nodeValue='New changes ';const small=$('stChange')?.parentElement?.querySelector('small');if(small)small.textContent='NEW CHANGES';const unreadStudents=new Set(notes.map(n=>n.studentId));document.querySelectorAll('#aggBody tr').forEach((tr,i)=>{tr.classList.toggle('newChangeRow',unreadStudents.has(S.students[i]?.id));if(unreadStudents.has(S.students[i]?.id)){const last=notes.find(n=>n.studentId===S.students[i].id);if(last){const td=tr.children[4];if(td)td.innerHTML='<span class="changedOK">已自動改課 · 請看紅色通知</span>'}}});renderCoachAlerts()};
renderStudent=function(){let s=st(),allowed=new Set(choicesFor(s)),b=bookings(s.id),dr=drafts(s.id).filter(id=>allowed.has(id)),z=status(s.id),req=S.changes[s.id],need=Math.max(0,s.sessions-b.length),last=S.lastChange[s.id],out='<div class="head"></div>'+D.map(x=>'<div class="head">'+x+'</div>').join('');S.drafts[s.id]=dr;$('hello').textContent='嗨，'+s.name+' 👋';$('portalProgress').textContent='本週 '+b.length+' / '+s.sessions+' 堂 · '+zhStatus(s.id);let step='',title='',text='',action='',targets=[];
if(req){step='舊版待處理需求';title='這筆需求仍等待 Eddie 處理';text=req.help?'你之前曾請 Eddie 幫忙安排。':'你之前的改課需求尚未完成。';action='<button class="btn" disabled>等待處理</button>'}
else if(changeMode){if(!changeFrom&&b.length===1)changeFrom=b[0];step='這週臨時改時間';if(!changeFrom){title='請選要更改的那一堂';text='先點下面一個已確認的粉紅色時段。';action='<button class="btn" id="cancelChange">取消</button>'}else{targets=liveTargets(s,changeFrom);title='直接選新的時間';text='下面只顯示 Eddie 現在真正有空的時段；點下去就會立即完成改課，不需要再等批准。';action='<div><span class="liveNote"><span class="liveDot"></span>即時空檔</span><button class="btn" id="cancelChange" style="margin-left:7px">取消</button>'+(targets.length?'':'<div class="noAvailability">目前沒有其他可改時段，請維持原本課程時間。</div>')+'</div>'}}
else if(z==='confirmed'){step=last?'本週改課完成':'本週已確認';title=last?'✅ 已完成改課':'你的本週課程已確認 ✓';text=last?(fmt(last.from)+' → '+fmt(last.to)+'。Eddie 會收到異動通知，不需要再批准。'):b.map(fmt).join(' · ');action='<button class="btn amber" id="requestChange">🔄 這週臨時改時間</button>'}
else if(need>0){step='步驟 1 — 選擇 '+need+' 個時間';title=dr.length?'目前已選：'+dr.map(fmt).join(' · '):'請選擇上課時間';text=dr.length===need?(need===1?'想換別的時間？直接點新的粉紅時段，會自動替換。':'如果想換其中一堂，直接點新的粉紅時段，再選要被取代的那一堂。'):'直接點下面粉紅色「點這裡選擇」的時段。';action='<button class="btn primary" id="confirmChoice" '+(dr.length!==need?'disabled':'')+'>✅ 確認本週課程</button>'}
else{step='步驟 2 — 確認';title='請確認本週課程';text=b.map(fmt).join(' · ');action='<button class="btn primary" id="confirmWeek">✅ 確認本週課程</button>'}
$('guideStep').textContent=step;$('guideTitle').textContent=title;$('guideText').textContent=text;$('guideAction').innerHTML=action;const targetSet=new Set(targets);
for(const h of H){out+='<div class="time">'+hh(h)+'<br>'+hh(h+1)+'</div>';for(let d=0;d<5;d++){let id=sid(d,h),cl='unavailable',t='不可選',sub='此時段目前不可使用';if(b.includes(id)){cl=changeMode?'changeFrom':'mine';t=changeMode?(changeFrom===id?'✓ 要更改這一堂':'點這堂來更改'):'✓ 已確認';sub=fmt(id)}else if(changeMode&&changeFrom&&targetSet.has(id)){cl='changeTarget';t='改到這個時間';sub=fmt(id)+' · 點一下立即完成'}else if(need>0&&allowed.has(id)){cl=dr.includes(id)?'selectedChoice':'allowed';t=dr.includes(id)?'已選擇':'點這裡選擇';sub=dr.includes(id)?fmt(id)+' · 再點可取消':fmt(id)}out+='<div class="sSlot '+cl+'" data-id="'+id+'"><div class="sCell"><b>'+t+'</b><small>'+sub+'</small></div></div>'}}$('studentCal').innerHTML=out;
if(!changeMode){document.querySelectorAll('#studentCal .allowed,#studentCal .selectedChoice').forEach(el=>el.onclick=()=>{let id=el.dataset.id,arr=drafts(s.id);if(arr.includes(id)){arr=arr.filter(x=>x!==id);S.drafts[s.id]=arr;save();renderStudent();return}if(arr.length<need){arr=[...arr,id];S.drafts[s.id]=arr;save();renderStudent();return}if(arr.length===need&&need===1){S.drafts[s.id]=[id];save();renderStudent();return}if(arr.length===need&&need>1){showReplacePicker(id,arr,s)}})}else{document.querySelectorAll('#studentCal .changeFrom').forEach(el=>el.onclick=()=>{changeFrom=el.dataset.id;renderStudent()});document.querySelectorAll('#studentCal .changeTarget').forEach(el=>el.onclick=()=>{if(!changeFrom)return;autoChange(s.id,changeFrom,el.dataset.id)})}
let cc=$('confirmChoice');if(cc)cc.onclick=()=>{let arr=drafts(s.id);if(arr.length!==need)return;for(const id of arr){if(!allowed.has(id))return;S.bookings[id]={studentId:s.id}}if(s.mode==='choices')Object.keys(S.holds).forEach(k=>{if(S.holds[k]?.studentId===s.id)delete S.holds[k]});delete S.drafts[s.id];delete S.lastChange[s.id];S.confirm[s.id]='confirmed';save();render()};let cw=$('confirmWeek');if(cw)cw.onclick=()=>{delete S.lastChange[s.id];S.confirm[s.id]='confirmed';save();render()};let rc=$('requestChange');if(rc)rc.onclick=()=>{changeMode=true;changeFrom=b.length===1?b[0]:null;renderStudent()};let cancel=$('cancelChange');if(cancel)cancel.onclick=()=>{changeMode=false;changeFrom=null;renderStudent()}}
window.addEventListener('storage',e=>{if(e.key!==K||!e.newValue)return;try{const incoming=JSON.parse(e.newValue);if(!incoming)return;S=incoming;S.notifications=S.notifications||[];S.weeklyOverrides=S.weeklyOverrides||{};S.lastChange=S.lastChange||{};S.changes=S.changes||{};S.drafts=S.drafts||{};S.line=S.line||{};render()}catch(err){}});
ensureCoachAlerts();render();